### ISSUE TITLE
ImportError: cannot import name 'AsyncContextManager'

### ISSUE THREAD

**Issue by Parnswir** [schul-cloud/antivirus_check_service#1]
Ich bekomme folgenden Output beim Start von scanurl, scanfile und webserver:

```
scanurl_1    | Traceback (most recent call last):
scanurl_1    |   File "/usr/local/bin/antivirus", line 11, in <module>
scanurl_1    |     load_entry_point('antivirus-service', 'console_scripts', 'antivirus')()
scanurl_1    |   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
scanurl_1    |     return get_distribution(dist).load_entry_point(group, name)
scanurl_1    |   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
scanurl_1    |     return ep.load()
scanurl_1    |   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
scanurl_1    |     return self.resolve()
scanurl_1    |   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
scanurl_1    |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
scanurl_1    |   File "/usr/src/app/antivirus_service/service.py", line 8, in <module>
scanurl_1    |     from antivirus_service.webserver import Webserver
scanurl_1    |   File "/usr/src/app/antivirus_service/webserver.py", line 6, in <module>
scanurl_1    |     import aio_pika
scanurl_1    |   File "/usr/local/lib/python3.5/dist-packages/aio_pika-5.4.0-py3.5.egg/aio_pika/__init__.py", line 1, in <module>
scanurl_1    |   File "/usr/local/lib/python3.5/dist-packages/aio_pika-5.4.0-py3.5.egg/aio_pika/patterns/__init__.py", line 1, in <module>
scanurl_1    |   File "/usr/local/lib/python3.5/dist-packages/aio_pika-5.4.0-py3.5.egg/aio_pika/patterns/master.py", line 7, in <module>
scanurl_1    |   File "/usr/local/lib/python3.5/dist-packages/aio_pika-5.4.0-py3.5.egg/aio_pika/channel.py", line 9, in <module>
scanurl_1    |   File "/usr/local/lib/python3.5/dist-packages/aio_pika-5.4.0-py3.5.egg/aio_pika/exchange.py", line 8, in <module>
scanurl_1    |   File "/usr/local/lib/python3.5/dist-packages/aio_pika-5.4.0-py3.5.egg/aio_pika/message.py", line 13, in <module>
scanurl_1    | ImportError: cannot import name 'AsyncContextManager'
```

Nach frischem Checkout und Installation mit docker-compose.

**Comment by Parnswir** [comment]
Läuft mit neu gebauten Images :-)
